# path to the task data directory
data_dir: null

# either provide a path to a plaintext file describing the task
desc_file: null
# or provide the task goal (and optionally evaluation information) as arguments
goal: null
eval: null

log_dir: log
log_level: INFO
workspace_dir: workspaces

# whether to unzip any archives in the data directory
preprocess_data: True
# whether to copy the data to the workspace directory (otherwise it will be symlinked)
# copying is recommended to prevent the agent from accidentally modifying the original data
copy_data: True

exp_name: null # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 1800
  agent_file_name: runfile.py
  format_tb_ipython: False

generate_report: False
# LLM settings for final report from journal
report:
  model: gpt-4o
  temp: 1.0

# agent hyperparams
agent:
  # how many improvement iterations to run
  steps: 20
  # total time available to agent
  time_limit: 86400 # 24 hrs (purely informational, implementation is user's resp)
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 5
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: True
  # whether to convert system messages into user messages
  convert_system_to_user: False
  # whether to obfuscate that we're doing kaggle
  obfuscate: True

  retriever:
    strategy: none # none, tricks
    model: gpt-4o-mini-2024-07-18
  analyzer:
    strategy: preview # none, preview
    model: gpt-4o-mini-2024-07-18
  planner:
    strategy: one-shot # one-shot
    model: gpt-4o
  coder:
    strategy: one-shot # one-shot, step-by-step
    model: gpt-4o
  improver:
    strategy: one-shot
    model: gpt-4o
  verifier:
    strategy: submission
    model: gpt-4o

  # hyperparameters for the tree search
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 5
    hpo_prob: 0.1
    max_hpo_prob: 0.3
    greedy_prob: 0.8
